### ISSUE TITLE
Cannot import name 'StashLogLevel'

### ISSUE THREAD

**Issue by papampi** [stg-annon/performerBodyCalculator#9]
Hi, 
Has not used the body calculator for long, today I tried it and  getting this error :

```
ERRO[2024-09-02 23:27:00] [Plugin / Performer Body Calculator] Traceback (most recent call last): 
ERRO[2024-09-02 23:27:00] [Plugin / Performer Body Calculator]   File "/home/payam/.stash/plugins/community/performerBodyCalculator-1.0/performer_body_calculator.py", line 4, in <module> 
ERRO[2024-09-02 23:27:00] [Plugin / Performer Body Calculator]     import config 
ERRO[2024-09-02 23:27:00] [Plugin / Performer Body Calculator]   File "/home/payam/.stash/plugins/community/performerBodyCalculator-1.0/config.py", line 1, in <module> 
ERRO[2024-09-02 23:27:00] [Plugin / Performer Body Calculator]     from stashapi.log import StashLogLevel 
ERRO[2024-09-02 23:27:00] [Plugin / Performer Body Calculator] ImportError: cannot import name 'StashLogLevel' from 'stashapi.log' (/root/.local/lib/python3.12/site-packages/stashapi/log.py) 
ERRO[2024-09-02 23:27:00] Plugin returned error: exit status 1    
```

Any idea how to solve it?

**Comment by stg-annon** [comment]
use the updated version of the plugin the repo was relocated [phashDuplicateTagger](https://github.com/stg-annon/StashScripts/tree/main/plugins/phashDuplicateTagger)
